### ISSUE TITLE
Invalid login or password

### ISSUE THREAD

**Issue by reklast** [PurpleHorrorRus/EasyVK-AudioAPI#1]
По какой-то причине не проходит авторизация

Код:
```
const { VK } = require("vk-io");
const AudioAPI = require("easyvk-audio");
require('dotenv').config();


const credits = {
	username: process.env.LOGIN,
	password: process.env.PASS,
	user: process.env.ID
};

const run = async () =>{
	try{
const VKClient = new VK({ token: process.env.VKTOKEN});
const API = await new AudioAPI(VKClient).login(credits);
} catch(err){
	console.error(err);
}
};

run();
```
сама ошибка:
```
{
  error: true,
  message: 'Invalid login or password',
  invalidCredits: true
}
```

Токен получаю через [vk-audio-token](https://github.com/vodka2/vk-audio-token), может ли быть проблема из-за этого?

При использовании стандартного метода получения токена через standalone приложение так же никаких успехов

**Comment by PurpleHorrorRus** [comment]
Выяснил, что ВК блочит слишком частые входы, возникает сервисная ошибка. Причём у меня эта ошибка возникла после первой попытки войти в аккаунт. Та же история и со страницой входа на самом сайте. Позже попробую разобраться...

**Comment by PurpleHorrorRus** [comment]
Встречный вопрос, пароль кириллицей?

**Comment by reklast** [comment]
Неа, кириллицы нету

**Comment by PurpleHorrorRus** [comment]
Загрузил фиксы в ветку meridius, должно работать

**Comment by reklast** [comment]
Да, все работает, спасибо
