### ISSUE TITLE
Broken login?

### ISSUE THREAD

**Issue by Dimacru** [PurpleHorrorRus/EasyVK-AudioAPI#2]
Похоже перестала работать аутентификация(

`npm run test                                                              ✔  5304  12:45:23

> easyvk-audio@1.6.1 test
> jest

 FAIL  tests/AudioAPI.test.js
  AudioAPI
    ✕ Get Audios

  ● AudioAPI › Get Audios

    TypeError: Cannot read properties of undefined (reading 'match')

      193 |
      194 |         return await this.actLogin({
    > 195 |             to: body.match(regex.LOGIN.TO)[1],
          |                      ^
      196 |             ip_h: body.match(regex.LOGIN.IP_H)[1],
      197 |             lg_domain_h: body.match(regex.LOGIN.LG_DOMAIN_H)[1],
      198 |             email: params.username,

      at HTTPClient.login (lib/http.js:195:22)
      at AudioAPI.login (index.js:23:23)
      at tests/AudioAPI.test.js:55:11

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.76 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.`

**Comment by PurpleHorrorRus** [comment]
Исправлено
